-- 1. Apaga a tabela de registros primeiro (por causa da FK)
DROP TABLE registros_colheita;

-- 2. Apaga a tabela de máquinas
DROP TABLE colhedoras;

-- 3. Agora crie a tabela de máquinas novamente
CREATE TABLE colhedoras (
    id_maquina VARCHAR2(20) PRIMARY KEY,
    modelo VARCHAR2(50) NOT NULL,
    vel_max_ideal NUMBER(4,2),
    rot_extrator_ideal NUMBER(4),
    altura_corte_ideal NUMBER(4,2)
);

-- 4. Crie a tabela de registros
CREATE TABLE registros_colheita (
    id_registro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_maquina VARCHAR2(20) NOT NULL,
    velocidade_real NUMBER(4,2),
    rotacao_real NUMBER(4),
    altura_real NUMBER(4,2),
    ton_esperada NUMBER(10,2),
    ton_realizada NUMBER(10,2),
    perda_percentual NUMBER(5,2),
    data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_maquina FOREIGN KEY (id_maquina) REFERENCES colhedoras(id_maquina)
);

-- 5. Insira os dados iniciais e dê COMMIT
INSERT INTO colhedoras VALUES ('JD-7000', 'John Deere S-Series', 5.0, 800, 5.0);
COMMIT;